name: Welcome Workflow

on: [push, pull_request]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Welcome Message
        run: echo "Welcome to GitHub Actions!"